// <auto-generated />
using System;
using LibraryCatalogNetCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryCatalogNetCore.Migrations
{
    [DbContext(typeof(LibraryCatalogDbContext))]
    [Migration("20220613181912_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("LibraryCatalogNetCore.Data.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatronId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("PatronId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryCatalogNetCore.Data.Patron", b =>
                {
                    b.Property<int>("PatronId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PatronId");

                    b.ToTable("Patrons");
                });

            modelBuilder.Entity("LibraryCatalogNetCore.Data.Book", b =>
                {
                    b.HasOne("LibraryCatalogNetCore.Data.Patron", null)
                        .WithMany("Borrowed")
                        .HasForeignKey("PatronId");
                });

            modelBuilder.Entity("LibraryCatalogNetCore.Data.Patron", b =>
                {
                    b.Navigation("Borrowed");
                });
#pragma warning restore 612, 618
        }
    }
}
